# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nicolas Oulianov
email: nicolas.oulianov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech, data science, programming, and more.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://oulianov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nicolasoulianov
github_username: oulianov

# Build settings
theme: just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# For copy button on code
enable_copy_code_button: true

# External navigation links
nav_external_links:
  - title: "GitHub"
    url: https://github.com/oulianov
  - title: "LinkedIn"
    url: https://www.linkedin.com/in/nicolas-oulianov/

aux_links_new_tab: false

permalink: pretty

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

math: katex
